// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $searchR from "./routes/searchR.tsx";
import * as $Heroe from "./islands/Heroe.tsx";
import * as $search from "./islands/search.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
    "./routes/searchR.tsx": $searchR,
  },
  islands: {
    "./islands/Heroe.tsx": $Heroe,
    "./islands/search.tsx": $search,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
