// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $contactos from "./routes/contactos.tsx";
import * as $dniinput from "./routes/dniinput.tsx";
import * as $index from "./routes/index.tsx";
import * as $dniinput_1 from "./islands/dniinput.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/contactos.tsx": $contactos,
    "./routes/dniinput.tsx": $dniinput,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/dniinput.tsx": $dniinput_1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
